name: flyingpigeon
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# - eggshell
##############
# analytic
- python=3
- numpy
# - ocgis  # moved to pip
- pandas
- gdal=2.4
##############
# plotting
- matplotlib
- cartopy
##############
# pip install
- pip:
  - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
  - -e git+https://github.com/NCPP/ocgis#egg=owslib
