name: flyingpigeon
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# - eggshell
##############
# analytic
- python=3
- numpy
- ocgis=2.1.0=py_3
- pandas
- gdal=2.2.4
##############
# plotting
- matplotlib
- cartopy
##############
# tests
- nose
##############
# pip install
- pip:
  - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
