name: flyingpigeon
channels:
- birdhouse
- conda-forge
- defaults
# ocgis
- nesii
# the r hell ...
- r
- bioconda  # for r-mclust
dependencies:
- python=2.7
- ipython
- gcc
#- glib=2.48.0
- pyopenssl
- cryptography
- psutil
- cffi
- setuptools=27.2.0
- icu=58.1
- libxslt
- pypdf2
################
# tests
- pytest
- nose
# pep8
- flake8
- pycodestyle
################
# docs
- sphinx
- sphinx_rtd_theme
- doc8
################
# wps
- nginx
- supervisor=3.3.1
- gunicorn
- gevent
- pywps=4.0.0
- mako
- genshi
################
# misc
#- pywget
- pyyaml=3.12
- jinja2=2
################
# numeric
- numpy
- scipy=1.1.0=py27_blas_openblas_200 # pinned due to issue #248
- pandas #=0.18.1
- statsmodels #=0.6.1
- scikit-learn #=0.17.1
################
# visualisation
- matplotlib=2.0.2=py27_2 #2.0.0=np112py27_2
- functools32=3.2.3.2=py27_0 # badly pinned matplotlib dependency
- cartopy
- iris
- reportlab
################
## cdo ocgis
- cdo=1.9.2=0
- hdf5=1.10.1=1
- libnetcdf=4.4.1.1=10
- ecmwf_grib=1.23.1=0
- python-cdo=1.3.3
- ocgis-next=2.1.0.dev1=py27_3
- icclim
- proj4=4.9.3
- geos=3.6.2=1
- jpeg=9b
- gdal=2.1.3=py27_7
# ################
# # analogue
- castf90=0.1.5
# ################
# # r
- cairo # for X11 independend plot support
- r=3.2  # 3.3 conflicts with icu=56
- rpy2 #=2.7.0
- r-mclust #=5.1 subsuituted by cluster
- r-ncdf4=1.15=1
- r-fields #=8.4 conflicts with r3.3.1 needs 3.2
- r-gridextra #=2.0.0
- harfbuzz
# #- r-cairo#=1.5_9 build in r-base
################
# esgf
- esgf-pyclient
- pip:
  - pygbif==0.2.0 #0.1.4
  - sphinx-autoapi==0.5.0
#  - cdo==1.3.0
