name: flyingpigeon
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=3
- pip
# - pywps=4.2
- jinja2
- click
- psutil
# - eggshell
##############
# analytic
- numpy
# - ocgis  # moved to pip
- pandas
- scikit-learn # for spatial_analog
- gdal=2.4
##############
# plotting
- matplotlib
- cartopy
##############
# tests
- pytest
- pytest-flake8
- nose
##############
# pip install
- pip:
  - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
  - -e git+https://github.com/NCPP/ocgis#egg=owslib
  - -e git+https://github.com/geopython/pywps.git#egg=pywps
