name: flyingpigeon
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# - eggshell
##############
# analytic
- python=3
- numpy
- ocgis
- pandas
##############
# plotting
- matplotlib
- cartopy
##############
# pip install
- pip:
  - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
