name: flyingpigeon
channels:
- conda-forge
- defaults
dependencies:
- python=3
- pip
- pywps=4.2.3
- jinja2
- click
- psutil
- psycopg2
# - eggshell
##############
# analytic
- numpy
- ocgis  # moved to pip (dependent eggshell ?)
- pandas
- scikit-learn # for spatial_analog
- gdal=2.4
##############
# plotting
- matplotlib
- cartopy
##############
# tests
- pytest
- pytest-flake8
- nose
##############
# pip install
- pip:
#  - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
#  - -e git+https://github.com/NCPP/ocgis#egg=owslib
  - sphinx_rtd_theme
  - nbsphinx
