# conda env create -f environment-docs.yml
name: flyingpigeon-docs
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- pywps>=4.2.7
- sphinx
- nbsphinx
- ipython
- ipywidgets
- pip
- pip:
  - https://github.com/metalink-dev/pymetalink/archive/master.zip
  - sphinx_rtd_theme
